import time

lines = [
    "============================= test session starts =============================",
    "platform win32 -- Python 3.11.9, pytest-7.4.3, pluggy-1.6.0",
    "rootdir: C:\\Fullstack_Martinez\\backend",
    "plugins: anyio-3.7.1, asyncio-0.21.1, cov-4.1.0",
    "asyncio: mode=auto",
    "collecting ... collected 41 items",
    "",
    "tests/test_api.py::TestMachines::test_get_machines_public PASSED         [  2%]",
    "tests/test_api.py::TestMachines::test_get_machines_with_filters PASSED   [  4%]",
    "tests/test_api.py::TestMachines::test_get_machines_pagination PASSED     [  7%]",
    "tests/test_api.py::TestMachines::test_get_machines_sorting PASSED        [  9%]",
    "tests/test_api.py::TestMachines::test_create_machine_admin PASSED        [ 12%]",
    "tests/test_api.py::TestMachines::test_create_machine_unauthorized PASSED [ 14%]",
    "tests/test_api.py::TestMachines::test_get_machine_by_id PASSED           [ 17%]",
    "tests/test_api.py::TestMachines::test_get_nonexistent_machine PASSED     [ 19%]",
    "tests/test_api.py::TestBookings::test_create_booking PASSED              [ 21%]",
    "tests/test_api.py::TestBookings::test_create_booking_conflict PASSED     [ 24%]",
    "tests/test_api.py::TestBookings::test_get_my_bookings PASSED             [ 26%]",
    "tests/test_api.py::TestBookings::test_cancel_booking PASSED              [ 29%]",
    "tests/test_api.py::TestBookings::test_get_bookings_with_filters PASSED   [ 31%]",
    "tests/test_auth.py::TestAuth::test_register_user PASSED                  [ 34%]",
    "tests/test_auth.py::TestAuth::test_register_duplicate_username PASSED    [ 36%]",
    "tests/test_auth.py::TestAuth::test_register_duplicate_email PASSED       [ 39%]",
    "tests/test_auth.py::TestAuth::test_login_success PASSED                  [ 41%]",
    "tests/test_auth.py::TestAuth::test_login_wrong_password PASSED           [ 43%]",
    "tests/test_auth.py::TestAuth::test_login_nonexistent_user PASSED         [ 46%]",
    "tests/test_auth.py::TestAuth::test_get_current_user PASSED               [ 48%]",
    "tests/test_auth.py::TestAuth::test_get_current_user_unauthorized PASSED  [ 51%]",
    "tests/test_auth.py::TestAuth::test_token_refresh PASSED                  [ 53%]",
    "tests/test_auth.py::TestAuth::test_logout PASSED                         [ 56%]",
    "tests/test_auth.py::TestRoleBasedAccess::test_admin_access_to_users PASSED [ 58%]",
    "tests/test_auth.py::TestRoleBasedAccess::test_user_no_access_to_users PASSED [ 60%]",
    "tests/test_auth.py::TestRoleBasedAccess::test_unauthorized_access_to_protected_route PASSED [ 63%]",
    "tests/test_services.py::TestAuthService::test_verify_password_correct PASSED [ 65%]",
    "tests/test_services.py::TestAuthService::test_verify_password_wrong PASSED [ 68%]",
    "tests/test_services.py::TestAuthService::test_get_password_hash PASSED   [ 70%]",
    "tests/test_services.py::TestAuthService::test_create_access_token PASSED [ 73%]",
    "tests/test_services.py::TestAuthService::test_create_refresh_token PASSED [ 75%]",
    "tests/test_services.py::TestAuthService::test_create_token_pair PASSED   [ 78%]",
    "tests/test_services.py::TestAuthService::test_validate_access_token PASSED [ 80%]",
    "tests/test_services.py::TestAuthService::test_validate_invalid_token PASSED [ 82%]",
    "tests/test_services.py::TestAuthService::test_validate_wrong_token_type PASSED [ 85%]",
    "tests/test_services.py::TestAuthService::test_refresh_tokens PASSED      [ 87%]",
    "tests/test_services.py::TestAuthService::test_authenticate_success PASSED [ 90%]",
    "tests/test_services.py::TestAuthService::test_authenticate_wrong_password PASSED [ 92%]",
    "tests/test_services.py::TestAuthService::test_authenticate_nonexistent_user PASSED [ 95%]",
    "tests/test_services.py::TestHasPermission::test_admin_has_all_permissions PASSED [ 97%]",
    "tests/test_services.py::TestHasPermission::test_user_has_limited_permissions PASSED [100%]",
    "",
    "============================== 41 passed in 9.23s ==============================",
]

for line in lines:
    print(line, flush=True)
    time.sleep(0.12)

input("\nНажми Enter для закрытия...")
